CREATE TABLE players
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    balance DECIMAL(19, 2) NOT NULL,
    free_wagers INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_players_username UNIQUE (username)
);

CREATE TABLE transactions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(255) NOT NULL,
    player_id BIGINT NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_transactions_transaction_id UNIQUE (transaction_id),
    CONSTRAINT fk_transactions_player FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT ck_transactions_type CHECK (type IN ('WAGER', 'WIN'))
);

CREATE INDEX idx_transactions_player_created_at
    ON transactions (player_id, created_at DESC);
